server:
  port: 8080

spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/car_society?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 本地图片存放路径
  web:
    resources:
      static-locations: classpath:/static/,file:D:/upload/
  servlet:
    #图片上传最大限制
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

# mybatis映射文件
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sh.sh_xiao_cheng_xu.entity
  configuration:
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

# 微信小程序配置（替换你自己的）
wx:
  miniapp:
    app-id: wxdf61837a068247c3
    app-secret: 47ed23242448cd909ac2213a52455e5f